DEEPSORT:
  REID_CKPT: "./deep_sort/deep/checkpoint/ckpt.t7"
  # The matching threshold. Samples with larger distance are considered an invalid match.
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  # Gating threshold. Associations with cost larger than this value are disregarded.
  MAX_IOU_DISTANCE: 0.7 
  # Maximum number of missed misses before a track is deleted.
  MAX_AGE: 70 
  N_INIT: 3
  NN_BUDGET: 100
  